services:
  backend:
    container_name: megaweave-backend
    image: ghcr.io/jasonjtw/megaweaving-backend:latest
    ports:
      - "8443:8443"
    env_file:
      - ./server/.env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - megaweave-net

  frontend:
    container_name: megaweave-frontend
    image: ghcr.io/jasonjtw/megaweaving-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.production
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - megaweave-net

  workbench:
    container_name: megaweave-workbench
    image: ghcr.io/pontusab/workbench-standalone:latest
    ports:
      - "9999:3000"
    environment:
      - QUEUE_NAMES=post-image
      - REDIS_URL=${WORKBENCH_REDIS_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - megaweave-net

networks:
  megaweave-net:
    driver: bridge
