version: '3.8'

services:
  backend:
    container_name: megaweave-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    env_file:
      - ./server/.env.production
    restart: unless-stopped
    networks:
      - megaweave-net

  frontend:
    container_name: megaweave-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
    ports:
      - "8282:8282"
    env_file:
      - ./client/.env.production
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - megaweave-net

networks:
  megaweave-net:
    driver: bridge
