// Serves the production build over HTTPS for E2E (npm run start:e2e).
// `next start` has no HTTPS option, and the session cookies are Secure, so a
// small proxy terminates TLS on :3100 and forwards to `next start` on :3101.
import { spawn } from "node:child_process";
import { readFileSync } from "node:fs";
import http from "node:http";
import https from "node:https";

const HTTPS_PORT = 3100;
const APP_PORT = 3101;

// Bind to "localhost", not an IP: with an IP hostname, next-intl's rewrites
// (e.g. / -> /zh-TW) resolve to a different origin and loop back as redirects.
const APP_HOST = "localhost";

const next = spawn(
  "npx",
  ["next", "start", "--port", String(APP_PORT), "--hostname", APP_HOST],
  { stdio: "inherit" },
);
next.on("exit", (code) => process.exit(code ?? 1));

const server = https.createServer(
  {
    // Generated by `next dev --experimental-https` locally, by the workflow in CI
    key: readFileSync("certificates/localhost-key.pem"),
    cert: readFileSync("certificates/localhost.pem"),
  },
  (req, res) => {
    const upstream = http.request(
      {
        host: APP_HOST,
        port: APP_PORT,
        path: req.url,
        method: req.method,
        headers: { ...req.headers, "x-forwarded-proto": "https" },
      },
      (upstreamRes) => {
        res.writeHead(upstreamRes.statusCode ?? 502, upstreamRes.headers);
        upstreamRes.pipe(res);
      },
    );
    // Not ready yet: Playwright keeps polling until it gets a 2xx-403
    upstream.on("error", () => {
      if (!res.headersSent) res.writeHead(502);
      res.end();
    });
    req.pipe(upstream);
  },
);
server.listen(HTTPS_PORT, () => {
  console.log(`E2E client: https://localhost:${HTTPS_PORT} -> :${APP_PORT}`);
});

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => {
    server.close();
    next.kill(signal);
  });
}
