//* signup.ts
import express, { NextFunction, Request, Response, Router } from "express";
import dotenv from "dotenv";
dotenv.config();
import { User } from "./types/user";
import { userRoles, UserSession } from "./schema";
import { SignupUserSchema } from "./validations";
import { hashPassword, generateSalt } from "./passwordHasher";
import { randomUUID } from "crypto";
import { authRateLimiter } from "./middleware/rateLimiter";

const router: Router = express.Router();
import { ResultSetHeader, RowDataPacket } from "mysql2";
import dbPool from "./utils/db";
import { createUserSession } from "./session";

// Apply tiered strict rate limiting to all auth signup routes
router.use(authRateLimiter);

router.post("/", async (req: Request, res: Response, next: NextFunction) => {
  console.log("API signup called");

  //* 1. Validate the input
  const user: User = {
    id: 0,
    username: req.body.username,
    email: req.body.email,
    password: req.body.password,
    salt: "",
    public_id: "",
    created_at: undefined,
  };
  try {
    SignupUserSchema.parse(user);
  } catch (error) {
    console.error(`Validation error:`, error);
    return next(error);
  }

  //* 2. Check if the user already exists
  let userExisted: boolean;
  let result: RowDataPacket | RowDataPacket[] | undefined;
  try {
    const [rows] = await dbPool.query<RowDataPacket[]>(
      "SELECT * FROM users WHERE email = ?",
      [req.body.email],
    );
    result = rows[0];
    console.log(`Check user exists result:`, result);

    /// user existed logic
    if (result) {
      userExisted = true;
      console.log(`User already exists`);
      return res.status(400).json({ errorMessage: "User already exists" });
    }

    userExisted = false;
  } catch (error) {
    console.error(`Error checking if user exists: `, error);
    console.log(`result`, result);
    return next(error);
  }
  console.log(`userExisted:`, userExisted);

  //* 3. Hash the password & Generate public_id
  const public_id = randomUUID();
  console.log("Generated public_id: ", public_id);
  const salt = generateSalt();
  const hashedPassword = await hashPassword(user.password, salt);
  user.password = hashedPassword;
  user.salt = salt;
  user.public_id = public_id;

  //* 4. Insert the user into the database
  try {
    const query = `INSERT INTO users (username, email, password, salt, providers, role, public_id) VALUES (?, ?, ?, ?, ?, ?, ? )`;
    const [result] = await dbPool.query<ResultSetHeader>(query, [
      user.username,
      user.email,
      user.password,
      user.salt,
      JSON.stringify(["native"]),
      userRoles[0], // default role is 'user'
      user.public_id,
    ]);
    console.log("Insert user result:", result);

    // Create corresponding user_profiles row
    await dbPool.query(
      "INSERT INTO user_profiles (user_id, contact_email, custom_name) VALUES (?, ?, ?)",
      [result.insertId, user.email, user.username],
    );

    // Fetch the newly created user to get the created_at timestamp generated by the database
    const [rows] = await dbPool.query<RowDataPacket[]>(
      "SELECT created_at FROM users WHERE id = ?",
      [result.insertId],
    );
    const dbUser = rows[0];
    if (dbUser && dbUser.created_at) {
      user.created_at =
        dbUser.created_at instanceof Date
          ? dbUser.created_at
          : new Date(dbUser.created_at);
    } else {
      user.created_at = new Date();
    }

    //* 5. create user session
    const userSession: UserSession = {
      userId: result.insertId,
      role: userRoles[0],
      username: user.username,
      email: user.email,
      public_id: user.public_id,
      joined_at: user.created_at || new Date(),
    };
    await createUserSession(userSession, req, res);
    console.log("User session created:", userSession);
    console.log("---------");
    /// remove sensitive data before sending response
    const { password: _password, salt: _salt, ...safeUser } = user;
    res.status(200).json({
      message: "Signup successful!",
      user: safeUser,
    });
  } catch (error) {
    return next(error);
  }
});

export default router;
